@startuml

start

repeat :User input;
repeat while (input is valid) is (     no)
->yes;

:send user input over UDP;

:process user input;

switch (user input)
case ( create robot )
    : Create new Humanoid Robot;
    : Add to TaskScheduler list of robots;
case ( assign task )
    if (robot task queue is not full AND\n robot is available) then (yes)
        : Assign task to robot;
    else (log failure)
        : Log task assignment failure;
    endif
case ( change mode )
    if (requested mode is current operating mode) then (yes)
        : Log no change made;
    else (no)
        : Change operating mode of AssemblyLine;
    endif
endswitch
stop
@enduml