@startuml

title Execution of Task

entity TaskScheduler as taskscheduler
entity HumanoidRobot as robot
queue RobotTaskQueue as robottaskqueue
queue TaskStack as taskstack
entity Task as task
database Logger as logger

activate taskscheduler
activate robot
activate task

alt quality check task
    robot -> task: execute task
    robot -> task: perform inspection
else assembly task
    robot -> task: execute task
    robot -> task: validate assembly
else transport task
    robot -> task: execute task
    robot -> task: check weight
end

robot -> robottaskqueue: remove task from queue
alt task failed
    alt task stack is not full
        taskscheduler -> taskstack: push task to stack of tasks to be redistributed
    else
        robot -> logger: log task stack full
    end
end

robot -> robot: reboot

@enduml
