@startuml

switch (Task type)
case ( Quality check task )
    : Execute task;
    : Perform inspection;
case ( Assembly task )
    : Execute task;
    : Validate assembly;
case ( Transportation Task )
    : Execute task;
    : Check weight;
endswitch

: Remove task from queue;
if (task failed) then (yes)
    if (task stack full) then (no)
        : Push task to task stack; 
    else (yes)
        : Log task stack full;
    endif
    : Reboot;
else (no)
endif

stop
@enduml