@startuml

start

: Generate task;

if (task scheduler task queue is full) then (yes)
    : Log task assignment failure;
else (no)
    : Enqueue to task scheduler task queue;
endif
if (operating mode is AUTOMATIC) then (yes)
    repeat
        repeat
            if (robot is available) then (yes)
                : Pop task from task stack;
                : Assign task to robot;
                : Set stack_task_assigned to true;
            else (no)
            endif
        repeat while (list of robots fully traversed?) is (no) not (yes)
        if (stack task was assigned?) then (no)
            : Log no available robots;
        else (yes)
        endif
    repeat while (more tasks on task stack?) is (yes) not (no)

    repeat
        repeat
            if (robot is available) then (yes)
                : Dequeue task from task queue;
                : Assign task to robot;
                : Set queue_task_assigned to true;
            else (no)
            endif
        repeat while (list of robots fully traversed?) is (no) not (yes)
        if (queue task was assigned?) then (no)
            : Log no available robots;
        else (yes)
        endif
    repeat while (more tasks in task queue?) is (yes) not (no)

else (operating mode is MANUAL)
    : Assign task user input;
    if (task is in task stack) then (yes)
        : Pop task from task stack;
    else (no)
        if (task is in task queue) then (yes)
            : Dequeue task from task queue;
        else (no)
            : Log that requested task does not exist;
        endif
    endif
    if (robot is available) then (yes)
        : Enqueue task to robot task queue;
    else (no)
        : Log task assign failure;
    endif
endif

stop

@enduml